version: '3'

services:
  sync-kivra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync-kivra
    restart: unless-stopped
    volumes:
      # Mount a directory to store the downloaded documents
      - ./data:/data

      # Replace arguments in the below command with your own values
    command: >
      your-ssn-here
      --interaction-provider ntfy
      --ntfy-topic your-private-topic
      --storage-provider=filesystem
      --base-dir=/data
